INSERT INTO ready_addresses ("tkmAddress", "ruAddress", "enAddress")
VALUES
  ('Arzuw', 'Арзув', 'Arzuw'),
  ('Atatürk köç.', 'Улица Ататурка', 'Ataturk str.'),
  ('"Altyn Asyr" Gündogar bazary (Jygyllyk)', '"Алтын Асыр" Гундогар Базары (Толкучка)', '"Altyn Asyr" Gundogar bazary (Jygyllyk)'),
  ('Arçabil şaýoly', 'Арчабиль Шаёлы', 'Archabil shayoly'),
  ('Bagyr', 'Багир', 'Bagyr'),
  ('Berzeňňi', 'Берзенги', 'Berzengi'),
  ('Bekrewe', 'Бекреве', 'Bekrewe'),
  ('Bedew', 'Бедев', 'Bedew'),
  ('Podwoýski köç. (Bitarap Türkmenistan şaýoly)', 'Ул. Подвойского (Битарап Туркменистан шаёлы)', 'Podwoyski str. (Bitarap Turkmenistan shayoly)'),
  ('Büzmeýin', 'Бузмеин', 'Buzmeyin'),
  ('Büzmeýin GRES', 'Бузмеин ГРЭС', 'Buzmeyin GRES'),
  ('Çandybil şaýoly', 'Чандыбиль шаёлы', 'Chandybil shayoly'),
  ('WDNH Söwda Merkezi', 'ВДНХ торговый центр', 'WDNH Mall'),
  ('1 mkr', '1 мкр', '1 mkr'),
  ('2 mkr', '2 мкр', '2 mkr'),
  ('3 mkr', '3 мкр', '3 mkr'),
  ('4 mkr', '4 мкр', '4 mkr'),
  ('5 mkr', '6 мкр', '5 mkr'),
  ('6 mkr', '5 мкр', '6 mkr'),
  ('8 mkr', '8 мкр', '8 mkr'),
  ('9 mkr', '9 мкр', '9 mkr'),
  ('10 mkr', '10 мкр', '10 mkr'),
  ('11 mkr', '11 мкр', '11 mkr'),
  ('30 mkr', '30 мкр', '30 mkr'),
  ('Howdan "A"', 'Гаудан "А"', 'Howdan "A"'),
  ('Howdan "B"', 'Гаудан "Б"', 'Howdan "B"'),
  ('Howdan "W"', 'Гаудан "В"', 'Howdan "W"'),
  ('Türkmenbaşy şaýoly', 'Ул. Туркменбаши шаёлы (Ленина)', 'Turkmenbashy shayoly'),
  ('Aýtakow (Oguzhan köç.)', 'Айтаково (Ул. Огузхана)', 'Aytakow (Oguzhan str.)'),
  ('14-nji tapgyr (Sowhozny köç.)', '14-й этап - Элитки (Ул. совхозная)', '14th tapgyr (Sowhozny str.)'),
  ('15-nji tapgyr', '15-й этап', '15th tapgyr'),
  ('Moskowskiý köç. (10 ýyl Abadançylyk şaýoly)', 'Ул. Московская (10 йыл Абаданчылык шаёлы)', 'Moskowskiy str. (10 year Abadanchylyk shayoly)'),
  ('Nebitgaz (Mir-Ýubileýny köç.)', 'Нефтегаз (Ул. Мира-Юбилейное)', 'Nebitgaz (Mir-Yubileyny str.)'),
  ('Olimpiýa şäherçesi', 'Олимпийский городок', 'Olimpic city'),
  ('Sowetskiý köç. (Garaşsyzlyk şaýoly)', 'Ул. Советская (Гарашсызлык шаёлы)', 'Sowetskiy str. (Garashsyzlyk shayoly)'),
  ('Garadamak', 'Гарадамак', 'Garadamak'),
  ('Garadamak Şor', 'Гарадамак шор', 'Garadamak Shor'),
  ('Gökje', 'Гёкдже', 'Gokje'),
  ('G.Kuliýew köç. (Obýezdnoý)', 'Ул. Г.Кулиева (Объездная)', 'G.Kuliyew str. (Obyezdnoy)'),
  ('Gurtly', 'Гуртли', 'Gurtly'),
  ('Dosaaf', 'Досааф', 'Dosaaf'),
  ('Kim raýon', 'Ким район', 'Kim rayon'),
  ('Köpetdag şaýoly', 'Кёпетдаг шаёлы', 'Kopetdag shayoly'),
  ('Köşi', 'Кёши', 'Koshi'),
  ('Parahat 1', 'Мир 1', 'Parahat 1'),
  ('Parahat 2', 'Мир 2', 'Parahat 2'),
  ('Parahat 3', 'Мир 3', 'Parahat 3'),
  ('Parahat 4', 'Мир 4', 'Parahat 4'),
  ('Parahat 5', 'Мир 5', 'Parahat 5'),
  ('Parahat 6', 'Мир 6', 'Parahat 6'),
  ('Parahat 7', 'Мир 7', 'Parahat 7'),
  ('Parahat 8', 'Мир 8', 'Parahat 8'),
  ('Gagarin köç. Köne Howa menzili', 'Старый Аэропорт ул. Гагарина', 'Gagarin str. Old Howa menzili'),
  ('Gypjak', 'Кипджак', 'Gypjak'),
  ('Ruhabat (90-njy razýezd)', 'Рухабат (90-й разъезд)', 'Ruhabat (90th razyezd)'),
  ('Täze Zaman', 'Тязе Заман', 'New Zaman'),
  ('"Berkarar" SDAM', 'ТЦ "Беркарар"', '"Berkarar" Mall'),
  ('Garaşsyzlygyň 15 ýyllygy (Optowka)', 'ТЦ "15 лет Независимости" (Оптовка)', 'Garashsyzlyk 15 year (Optowka)'),
  ('Çoganly', 'Чоганлы', 'Choganly'),
  ('Hitrowka', 'Хитровка', 'Hitrowka'),
  ('Herrikgala', 'Херрикгала', 'Herrikgala'),
  ('Şor Daça', 'Шор Дача', 'Shor Dacha'),
  ('Ýalkym', 'Ялкым', 'Yalkym'),
  ('Ýanbaş', 'Янбаш', 'Yanbaş'),
  ('16-njy tapgyr', '16-й этап', '16th tapgyr');
